# Generated by Django 5.0 on 2024-10-12 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('numero', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], default='M', max_length=1)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
