# Generated by Django 5.0 on 2024-10-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='num_id',
            field=models.CharField(default=123, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
