# Generated by Django 5.0 on 2024-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_num_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
